chore: demonstrate array items missing issue
Demonstrates two failure cases which need improved error responses.

When the `items:` property of a schema is missing for `type: array`,
Sweater Comb fails with errors that are hard to parse:

```
$ node build/index.js compare --to ./end-end-tests/api-standards/resources/thing/2021-11-10/000-fail-array-missing-items.yaml  --context "$(cat ./end-end-tests/api-standards/context.json)"
Loading spec files
Specs loaded - running comparison
Comparing Empty Spec to ./end-end-tests/api-standards/resources/thing/2021-11-10/000-fail-array-missing-items.yaml

Cannot use 'in' operator to search for '$ref' in undefined
```

If the type of `items:` is invalid, sweater-comb crashes:

```
zksnyk:sweater-comb cmars$ node build/index.js compare --to ./end-end-tests/api-standards/resources/thing/2021-11-10/000-fail-array-invalid-items.yaml --context "$(cat ./end-end-tests/api-standards/context.json)"
Loading spec files
Stopping. Could not load two specifications to compare
Error: [{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data/items","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data/items","schemaPath":"#/properties/items/anyOf/1/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data/items","schemaPath":"#/properties/items/anyOf","keyword":"anyOf","params":{},"message":"must match a schema in anyOf"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"type"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"items"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema/properties/data","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"type"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"description"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"properties"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200/content/application~1vnd.api+json/schema","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"description"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"headers"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"content"},"message":"must NOT have additional properties"},{"instancePath":"/paths/~1orgs~1{org_id}~1thing/get/responses/200","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data/items","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data/items","schemaPath":"#/properties/items/anyOf/1/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data/items","schemaPath":"#/properties/items/anyOf","keyword":"anyOf","params":{},"message":"must match a schema in anyOf"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"type"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"items"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollectionResponse/properties/data","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/components/schemas/ThingCollectionResponse","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/components/schemas/ThingCollectionResponse","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"type"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollectionResponse","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"description"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollectionResponse","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"properties"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollectionResponse","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/components/schemas/ThingCollection/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/components/schemas/ThingCollection/items","schemaPath":"#/type","keyword":"type","params":{"type":"object"},"message":"must be object"},{"instancePath":"/components/schemas/ThingCollection/items","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"},{"instancePath":"/components/schemas/ThingCollection/items","schemaPath":"#/properties/items/anyOf/1/type","keyword":"type","params":{"type":"array"},"message":"must be array"},{"instancePath":"/components/schemas/ThingCollection/items","schemaPath":"#/properties/items/anyOf","keyword":"anyOf","params":{},"message":"must match a schema in anyOf"},{"instancePath":"/components/schemas/ThingCollection","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"$ref"},"message":"must have required property '$ref'"},{"instancePath":"/components/schemas/ThingCollection","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"type"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollection","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"items"},"message":"must NOT have additional properties"},{"instancePath":"/components/schemas/ThingCollection","schemaPath":"#/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"}]
    at validateOpenApiV3Document (/Users/cmars/Projects/sweater-comb/node_modules/@useoptic/openapi-utilities/build/openapi3/implementations/openapi3/validator.js:17:15)
    at /Users/cmars/Projects/sweater-comb/node_modules/@useoptic/api-checks/build/ci-cli/commands/compare/compare.js:120:63
    at async Promise.all (index 1)
```