fix: add commander dependency
Fixes an issue with `npm pack` redistributions of `@snyk/sweater-comb`,
which were unable to run with this error:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /Users/cmars/Projects/node-service-sample/node_modules/@snyk/sweater-comb/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/cmars/Projects/node-service-sample/node_modules/@snyk/sweater-comb/build/index.js:42:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cmars/Projects/node-service-sample/node_modules/@snyk/sweater-comb/build/index.js'
  ]
}
```